config/routes.rb
Rails.application.routes.draw do

  resources :wikis
  resources :collaborators, only: [:create, :destroy]



  resources :charges, only: [:new, :create]

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/wikis'

  get 'charges/cancel' => 'charges#cancel', as: :cancel_premium
  post 'charges/cancel' => 'charges#destroy', as: :cancel_premium_post

  devise_for :users

  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborators

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  enum role: [:member, :admin, :premium]

  before_save { self.role ||= :member }


  def downgrade_user!
    self.update(role: 0)
    private_wikis =  Wiki.where(user_id: self.id, private: true)
    private_wikis.each do |wiki|
      wiki.private = false
      wiki.save
    end
  end

  def self.all_except(user)
    where.not(id: user)
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  def public?
    !private
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )

   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 15_00,
     description: "BigMoney Membership - #{current_user.email}",
     currency: 'usd'
   )

   flash[:notice] = "Thank you for your payment, #{current_user.email}. You are now a premium member and can make private wikis!"
   current_user.update(role: 2)
   redirect_to welcome_index_path

   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.name}",
      amount: 15_00
    }
  end

  def destroy
    current_user.downgrade_user!
    current_user.update(role:0)
  end

end

app/controllers/collaborators_controller.rb
require 'pp'
class CollaboratorsController < ApplicationController

  def create
    pp params
    user_id = params[:collaborator][:user_id]
    wiki_id = params[:collaborator][:wiki_id]
    puts user_id
    collaborator = Collaborator.new(user_id: user_id, wiki_id: wiki_id)

    @wiki = Wiki.find(wiki_id)

    if collaborator.save
      flash[:notice] = "The collaborator has been saved and now has access to this Wiki."
      redirect_to :back
    else
      flash.now[:alert] = "The collaborator has not been saved. Please try again."
      redirect_to :back
    end

  end


  def destroy

    collaborator = Collaborator.find(params[:id])

    if collaborator.destroy
      flash[:notice] = "The collaborator was deleted successfully."
      redirect_to :back
    else
      flash.now[:alert] = "There was an error removing the collaborator."
      redirect_to :back
    end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include Pundit

  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include Pundit
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def authorize_user
    wiki = Wiki.find(params[:id])
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to wikis_path
    end
  end

  def create
    @wiki = Wiki.new
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user = current_user
    @wiki.private = params[:wiki][:private] === "1"


    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def index
    @wikis = policy_scope(Wiki)
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    #@wiki.collaborators = params[:wiki][:collaborators].split(',')

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper

  def find_collaborator(user, wiki)
    Collaborator.where(user_id: user.id, wiki_id: wiki.id).first
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true,
    :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :lax_html_blocks => true,
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/charges/cancel.html.erb
<h1>Cancel Premium Membership </h1>
<h4>We are sorry to lose you. Please note that if you cancel now
and want to become a premium member in the future you will need to pay the
premium fee.</h4>

<%= link_to "Cancel Premium", cancel_premium_path, method: :create, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to cancel your premium membership?'} %>

app/views/charges/destroy.html.erb
<h3>Welcome back Member! You can create and update public wikis!</h3>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>"></script>
<% end %>

app/views/collaborators/_collaborator_form.html.erb
<div class="container">
  <% User.all_except(current_user).each do |user| %>
  <div class="row">
    <div class="col">
      <h3><%= user.email %></h3>
    </div>
    <div class="col">
      <% if wiki.users.include?(user) %>
        <%= link_to "Remove Collaborator", find_collaborator(user, wiki), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= form_for Collaborator.new do |f| %>
          <%= f.hidden_field :user_id, value: user.id %>
          <%= f.hidden_field :wiki_id, value: wiki.id %>
          <%= f.submit 'Make Collaborator', class: "btn btn-success" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
        <div class="pull-right ">
          <%-# checks if user is signed in -%>
          <% if user_signed_in? %>
          Signed in as:
          <strong><%= current_user.email %></strong>
          |
          <%unless current_user.premium?%>
            <%= link_to 'Upgrade Account' + " -", new_charge_path, :class => 'navbar-link' %>
          <% else %>
            <%= link_to 'Cancel Premium' + " -", cancel_premium_path, :class => 'navbar-link' %>
          <% end %>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
          -
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>

          <%- #display Sign Up and Sign In buttons if user not logged in -%>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
          -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>

        </div>

        <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
        <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
        <% end %>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>

      </body>
    </html>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Blocipedia is a Ruby on Rails application that is designed to be a collaborative wikipedia page!</p>

app/views/welcome/index.html.erb
<h1 style="text-align:center">Welcome to Blocipedia!</h1>

app/views/wikis/_form.html.erb
<div class="container">
  <div class="col-md-8">
    <%= form_for wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki Title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' %>
          <%= f.check_box :private %>
          Private wiki
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/delete.html.erb
<h1>Wikis#delete</h1>
<p>Find me in app/views/wikis/delete.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="container">
  <div class="col-md-8">
      <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki Title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' %>
          <%= f.check_box :private %>
          Private wiki
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      <% end %>
  </div>
</div>

<h2>Collaborators</h2>
<% if current_user.admin? || current_user.premium? && @wiki.private? %>
  <%= render partial: 'collaborators/collaborator_form', locals: { wiki: @wiki } %>
<% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% if policy(:wiki).create? %>
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% end %>

<% @wikis.each do |wiki| %>
  <p><%= link_to wiki.title, wiki_path(wiki) %></p>
  <% if policy(wiki).update? %>
    <%= link_to "Edit Wiki", edit_wiki_path(wiki), class: 'btn btn-info' %>
  <% end %>
<% end %>

app/views/wikis/new.html.erb
</div>
  <%= render partial: "form", locals: {wiki: @wiki} %>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <% if policy(@wiki).update? %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <% end %>
  </div>
</div>